### ISSUE TITLE
[Feature Request] Configurable drop delay for stacks of items

### ISSUE THREAD

**Issue by calloatti** [ModsByLeo/DontDropIt#1]
When you have a stack of cobblestone for example, and you press Q, the drop delay is applied to the first item, and also to all the subsequent items while you hold Q down.

It would be nice to have a configuration option where the drop delay is only applied to the first item of a stack, and the next items of the same stack drop instantly until you let go Q.

**Comment by Leo40Git** [comment]
v1.1.0 now includes this feature. It can be downloaded from [GitHub Releases](https://github.com/Leo40Git/DontDropIt/releases) or [CurseForge](https://www.curseforge.com/minecraft/mc-mods/dont-drop-it).
