### ISSUE TITLE
Feature Request: Favourited items can't be shift-clicked through inventories

### ISSUE THREAD

**Issue by ProfanedBane** [ModsByLeo/DontDropIt#10]
Quick feature request, I'll likely get to PRing it in the coming weeks when I find the time/get my IDE setup again.

Ideal is that a favourited item does not get transferred between inventories by shift clicking, perhaps we can even check for what type of inventory it's trying to move to (hopper/chest/shulker etc) and whitelist certain ones.

Usecase for this is incinerators or hopper contraptions that you would rather not lose your +100000 Diamond Sword to by mistake.

Ofc with options and such for those who would rather keep functionality as is.

**Comment by Leo40Git** [comment]
this should be pretty easy to do, no need for the PR (I appreciate it, though!)
