### ISSUE TITLE
1.16.4 Don't work

### ISSUE THREAD

**Issue by TestItDev01** [ModsByLeo/DontDropIt#15]
It loads in 1.16.4 whitout error .... but it dont work !
q drops the items ... whatever settings ...

 

Tested on
Minecraf 1.16.4
FabricLoader 0.10.8
Don't Drop it 2.1.0+1.16
FabicAPI 0.28.0+1.16

1.16.3 works fine ... no problems ...

 

I tried rebuilding the plugin for 1.16.4 but it seems it needs more than changing the gradle.properties :( 

Actual yarn-1.16.4+build.7-v2 has no ClickWindowC2SPacket and ConfirmGuiActionS2CPacket ....

I made some simple buckit plugins ... but this stuff is beyond my level ....

Last working MC is 1.16.3

**Comment by Leo40Git** [comment]
Thank you for the issue report.
Issue has been verified.

**Comment by Leo40Git** [comment]
Fixed in 2.2.0.
