### ISSUE TITLE
When drop stack key is set to same as sneak/crouch control, player can't sneak/crouch

### ISSUE THREAD

**Issue by frugbug** [ModsByLeo/DontDropIt#2]
I usually have my sneak key set to Left-Ctrl, which is also the default keybind for the "drop all stacks" action in this mod. It works fine in vanilla (I can sneak using Left-Ctrl, and also drop all stacks using Left-Ctrl). But with this mod installed it won't let me sneak.
The same thing happens when the sneak key and drop all items key are both set to shift.

**Comment by Leo40Git** [comment]
This is just Vanilla being dumb about conflicting keybindings, I think. I'll look into it and see if I can fix it.
