### ISSUE TITLE
Delay Drop Favorite Option

### ISSUE THREAD

**Issue by LOLboy199** [ModsByLeo/DontDropIt#22]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Related problem

I like both the Delay Drop and the Favorites features. A good option would be to have an option to switch from never dropping favorite items to delay drop for favorite items, separate from delay drop of all items. This would for example, allow an even longer delay drop for favorites compared to all other items. 

### Suggested solution

Personally, I think a good spot for the option would be two new buttons on the Favorites tab in the configuration menu. Somewhere in the top section, like below the 'draw overlay' button for example would be a good location. Add one button for 'Enable Drop Delay for Favorites' Yes/No (button); and then another for the "Hold Ticks for Favorites" with a slider value bar. These buttons could have the same look and functions as the normal drop delay ones just with "Favorites" added or whatever. 

### Alternative solutions

 You could also put the buttons on the Drop Delay tab instead since there isn't much on that tab and it would save space on the favorites tab. Not sure what the best option is.

**Comment by LOLboy199** [comment]
Sorry I don't know how to change the label from 'bug' to 'enchancement' I had to make a GetHub account so I could make these posts.

**Comment by Leo40Git** [comment]
~~There's a form for feature requests specifically which adds the correct label, but whatever, fixing it is literally two clicks.~~

Wait, no, this _is_ the feature request form. Oops.
