### ISSUE TITLE
Game won;t start with this mod

### ISSUE THREAD

**Issue by keatit71** [ModsByLeo/DontDropIt#26]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version information

v2.3.5 for 1.18

### Expected Behavior

Game to start

### Actual Behavior

Game crashes 

### Reproduction Steps

Install mod from modrinth

run game

### Java version

java 17

### Additional information

[mod.txt](https://github.com/ModsByLeo/DontDropIt/files/7670828/mod.txt)

**Comment by Leo40Git** [comment]
Please provide a crash report.
See [here](https://fabricmc.net/wiki/player:tutorials:logs_ml:windows) how to get the crash report on Windows or Linux, or [here](https://fabricmc.net/wiki/player:tutorials:logs_ml:mac) for MacOS.
Then, upload the crash report to a paste site, like [Pastebin](https://pastebin.com) or GitHub's very own [Gist](https://gist.github.com).

**Comment by keatit71** [comment]
i got the newest version seems like it won;t work with inventory control tweaks so i'm guessing thats the problem.

**Comment by Leo40Git** [comment]
Oh, yeah, there's a mixin conflict between the two mods that cannot be worked around. Sorry.
