### ISSUE TITLE
Default Favourite Item/Enchantment IDs are always restored

### ISSUE THREAD

**Issue by sorat0mo** [ModsByLeo/DontDropIt#28]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version information

2.3.7 for 1.18

### Expected Behavior

The config should be saved when I delete them through Mods Menu _or_ directly editing the config file in config/dontdropit.json5

### Actual Behavior

The config is reset to default after every start of the game.

### Reproduction Steps

1. Remove ID by editing config directly
2. Start the game

or:
1. Remove ID ingame
2. Save & Quit
3. Exit the game
4. Relaunch the game and load into the world

### Java version

OpenJDK 17

### Additional information

I am using MultiMC.
I installed Cloth Config v6 (latest), Fabric API, Mod Menu
I have not installed: Amecs, Auto Config Update API, Mod Updater.

Auto Config Update API says it is migrated to Cloth Config, please clarify whether I need it installed to work.

**Comment by Leo40Git** [comment]
> I installed Cloth Config v6 (latest), Fabric API, Mod Menu

Just noticed this - you do _not_ need to install the mod's dependencies, as the mod bundles them.
