### ISSUE TITLE
Mod doesn't recognise enchanted tools

### ISSUE THREAD

**Issue by j7j11** [ModsByLeo/DontDropIt#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version information

dontdropit-2.4.0+1.18 + mc1.18.2

### Expected Behavior

Enchanted items with the enchantments listed on favorites should not drop, but that only occurs with books

![image](https://user-images.githubusercontent.com/16526803/169848796-46446751-e2de-4866-8502-62ab7f520495.png)

![image](https://user-images.githubusercontent.com/16526803/169848861-e64f31af-dcce-4c65-9042-059efd2787d7.png)

### Actual Behavior

The tools are not locked and can still drop

### Reproduction Steps

1. Item Selected
2. Enchantment is on the list
3. Can still drop a pickaxe for example
5. Can't drop the enchantment book

### Java version

Java 17.0.1

**Comment by Leo40Git** [comment]
Well, I know precisely where this bug is happening, at least...

**Comment by j7j11** [comment]
Thx for the quick fix
