### ISSUE TITLE
no 1.19

### ISSUE THREAD

**Issue by SuperSurferNow** [ModsByLeo/DontDropIt#34]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Related problem

add 1.19

### Suggested solution

by adding 1.19

### Alternative solutions

shuting down this github

**Comment by Leo40Git** [comment]
> ### Alternative solutions
> shuting down this github

Gee, thanks.

A 1.19 update will be coming though, I've just been distracted by other projects.

**Comment by Leo40Git** [comment]
there I updated it you jerk /hj
