### ISSUE TITLE
Don't Drop It! v1.3.0 - Log Spam in Inventories

### ISSUE THREAD

**Issue by rxay579** [ModsByLeo/DontDropIt#6]
Getting a ton of errors spammed in the log with DDI v1.3.0.

Tested with fresh MultiMC instance with MC v1.16.1, Fabric API Loader (v0.9.0), DDI (v1.3.0), and Fabric API (v0.16.2b385).
Tested again with the above and with ModMenu (v1.14.5).

[main/ERROR]: ########## GL ERROR ##########
[main/ERROR]: @ Pre render
[main/ERROR]: 65539: Invalid key -1

Latest Log (first test):
[latest.log](https://github.com/Leo40Git/DontDropIt/files/5038410/latest.log)

Latest Log (send test):
[latest.log](https://github.com/Leo40Git/DontDropIt/files/5038446/latest.log)

**Comment by Leo40Git** [comment]
*Finally* fixed by 6d3be45573686f0001765bf769b2c20ecdb8fd33.
I blame Mojang.

**Comment by Leo40Git** [comment]
v1.3.1 is [out here on GH](https://github.com/Leo40Git/DontDropIt/releases/tag/v1.3.1%2B1.16) and is currently being processed on CF.
