### ISSUE TITLE
Typing a Non-alpha-numeric character on Config Screen causes a game crash.

### ISSUE THREAD

**Issue by FavoritoHJS** [ModsByLeo/DontDropIt#7]
Tested with Don't Drop It! 1.4.0+1.16, Fabric API 0.17.2+build.396-1.16, Cloth Config v4 4.7.0-unstable, Mod Menu 1.14.6+build.31

-- Expected Result: Wouldn't even let me type the character.
-- Actual Result: Game crashed!

-- Mods Required:
- Don't Drop It!
- Mod Menu

-- Replication
- Step 1: Press the "Mods" button
- Step 2: Open the configuration of "Don't Drop It!"
- Step 3: Go to the "Favorites" tab
- Step 4: Make a new entry on a list.
- Step 5: Place a non-alphanumeric character on an entry
- Step 6: [Crash.](https://github.com/Leo40Git/DontDropIt/files/5077999/crash-2020-08-14_21.50.27-client.txt)

[Note: This might be a problem outside of "Don't Drop It"s control,]

**Comment by Leo40Git** [comment]
actually this one's on me, whoops

**Comment by Leo40Git** [comment]
https://github.com/Leo40Git/DontDropIt/commit/120dbb5101e7ecd548f6d6f4382ad65933d4905f should fix this

**Comment by Leo40Git** [comment]
v1.4.1 has been released with a fix for this issue.
