### ISSUE TITLE
Game Crashes upon Startup with Missing or Corrupt Config

### ISSUE THREAD

**Issue by FavoritoHJS** [ModsByLeo/DontDropIt#8]
[Crash Log](https://github.com/Leo40Git/DontDropIt/files/5079863/crash-2020-08-15_22.18.48-client.txt) | [Game Log](https://github.com/Leo40Git/DontDropIt/files/5079865/latest.log)
- Expected Result: Invalid Config gets regenerated.
- Actual Result: Game Crashes.

fabric: Fabric API 0.17.2+build.396-1.16
dontdropit: Don't Drop It! 1.4.1+1.16
Java 14.0.1.7 [In case that matters…]
I'm 99% certain this is PEBKAC.

**Comment by Leo40Git** [comment]
I'm pretty sure your config got corrupted somehow.
Please delete `config/dontdropit.json` and try again.

**Comment by FavoritoHJS** [comment]
[Config deleted,](https://user-images.githubusercontent.com/69703458/90338556-72218f80-dfb8-11ea-8a15-6cae3250186b.png), [Game still crashed.](https://github.com/Leo40Git/DontDropIt/files/5080960/crash-2020-08-16_12.04.24-client.txt)

**Comment by Leo40Git** [comment]
it's in `.minecraft/config`, not in `.minecraft`

**Comment by FavoritoHJS** [comment]
[Deleted the Config File](https://user-images.githubusercontent.com/69703458/90339008-dbef6880-dfbb-11ea-9e23-e0ff1d690781.png), the game still crashed and no config file was created.

**Comment by FavoritoHJS** [comment]
Just tested, game boots up fine in 1.4.0

**Comment by Leo40Git** [comment]
Cheers. I'll see what I can do to prevent this "corruption" later.

**Comment by FavoritoHJS** [comment]
A [Config File](https://github.com/Leo40Git/DontDropIt/files/5081147/dontdropit.json.txt) that worked perfectly fine in 1.4.0 breaks in 1.4.1.
In case you can't reproduce this, I'm using OpenJDK14 on a MultiMC instance in the E:\ drive.

**Comment by Leo40Git** [comment]
i... misread that comment immensely, oops

**Comment by Leo40Git** [comment]
OH WAIT FUCK I KNOW WHY IT'S CRASHING
