### ISSUE TITLE
GL ERROR log spam when mouse cursor is inside an inventory

### ISSUE THREAD

**Issue by ProfanedBane** [ModsByLeo/DontDropIt#9]
https://github.com/Leo40Git/DontDropIt/issues/6 has returned and wants revenge.

When you have an inventory screen open, if the mouse is selecting a slot the below error is spammed. Removing the mouse from the slot or closing the inventory ceases the spam.

All controls for DontDropIt are bound to a key.

[20:41:53] [main/ERROR]: ########## GL ERROR ##########
[20:41:53] [main/ERROR]: @ Render
[20:41:53] [main/ERROR]: 65539: Invalid key -1

**Comment by Leo40Git** [comment]
that... definitely should not be happening. 
the fix for #6 should've prevented another error like this... 
what version are you using?

**Comment by ProfanedBane** [comment]
Fabric reports 1.4.2+1.16, filename is 'dontdropit-1.4.2+1.16.jar'.
Downloaded from the CurseForge files page for the mod.

Minecraft 1.16.2
Fabric API 0.19.0+build.398-1.16
Fabric Loader 0.9.1+build.205

Also to sanity check I disabled all my other mods and the issue still occurs with just DontDropIt and Fabric API.
Issue is still present when AMECs is installed if that makes any difference.

Also to clarify the errors are only when one of the little inventory slot squares has the cursor over it.

**Comment by Leo40Git** [comment]
can't reproduce in a dev environment, will try production environment later

**Comment by ProfanedBane** [comment]
Give me a shout if it doesn't work with whatever's on Curseforge in a regular game, I'll have a more in depth look if nothing turns up.

**Comment by ProfanedBane** [comment]
To add on this also appears to be happening at any time a key is being pressed, including movement etc.

**Comment by ProfanedBane** [comment]
I THINK I've found how to reproduce this.
It appears you additionally need to have the "drop selected item" key unbound. The one that's usually 'Q'.
As a sanity check I tried unbinding it in an unmodded instance and the error doesn't occur.

**Comment by Leo40Git** [comment]
OH
hm, yeah, that should be easy to fix then
